options:
  logging: NONE  # This option disables all logging

steps:
  # Step to activate virtual environment and install dbt
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m venv /workspace/venv
        source /workspace/venv/bin/activate
        pip install dbt-snowflake==1.7.1
        dbt deps

  # Step to run linting with proper handling of local variables
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD --diff-filter=d | grep '\.sql$')
        if [ ! -z "${CHANGED_FILES}" ]; then
          pip install sqlfluff
          sqlfluff lint --config .sqlfluff ${CHANGED_FILES}
        else
          echo "No SQL files to lint."
        fi

  # Step to run dbt commands based on conditions
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "${_DBT_TARGET}" != "none" ]]; then
          dbt run --target ${_DBT_TARGET}
          dbt test --target ${_DBT_TARGET}
        fi

# Define substitution variables that might be used
substitutions:
  _DBT_TARGET: 'dev'
